services:
  vmb-app:
    image: localhost/projectmanagement
    container_name: vmb
    ports:
      - 8003:8003
    volumes:
      - ./data:/data/vmb
    environment:
      - DEBUG=1
  vmb-mcp-app:
    image: localhost/budget-mcp
    container_name: vmb-mcp
    ports:
      - 8004:8080
    environment:
      # Crucial change: We now point to the 'django-web' service name on port 8000
      - DJANGO_API_URL=http://vmb-app:8003/api
      - PYTHONUNBUFFERED=1
    depends_on:
      - vmb-app
    # ADD THIS: Mounts your current directory (.) to /workspace inside the container
    volumes:
      - /Users/sweimann/development/dorette:/workspace
    stdin_open: true 
    tty: false
